In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv('credit_card.csv')
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[ 20000      2      2 ...      0      0      0]
 [120000      2      2 ...   1000      0   2000]
 [ 90000      2      2 ...   1000   1000   5000]
 ...
 [ 30000      1      2 ...   4200   2000   3100]
 [ 80000      1      3 ...   1926  52964   1804]
 [ 50000      1      2 ...   1000   1000   1000]]


In [4]:
print(y)

[1 1 0 ... 1 1 1]


In [5]:
X = np.array(X)

In [6]:
print(X)

[[ 20000      2      2 ...      0      0      0]
 [120000      2      2 ...   1000      0   2000]
 [ 90000      2      2 ...   1000   1000   5000]
 ...
 [ 30000      1      2 ...   4200   2000   3100]
 [ 80000      1      3 ...   1926  52964   1804]
 [ 50000      1      2 ...   1000   1000   1000]]


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
ann = tf.keras.models.Sequential()

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [12]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [13]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
750/750 [==============================] - 1s 947us/step - loss: 0.5640 - accuracy: 0.7366
Epoch 2/100
750/750 [==============================] - 1s 925us/step - loss: 0.4626 - accuracy: 0.8087
Epoch 3/100
750/750 [==============================] - 1s 933us/step - loss: 0.4500 - accuracy: 0.8138
Epoch 4/100
750/750 [==============================] - 1s 981us/step - loss: 0.4469 - accuracy: 0.8159
Epoch 5/100
750/750 [==============================] - 1s 913us/step - loss: 0.4390 - accuracy: 0.8206
Epoch 6/100
750/750 [==============================] - 1s 985us/step - loss: 0.4474 - accuracy: 0.8136
Epoch 7/100
750/750 [==============================] - 1s 1ms/step - loss: 0.4388 - accuracy: 0.8178
Epoch 8/100
750/750 [==============================] - 1s 976us/step - loss: 0.4398 - accuracy: 0.8178
Epoch 9/100
750/750 [==============================] - 1s 964us/step - loss: 0.4389 - accuracy: 0.8174
Epoch 10/100
750/750 [==============================] - 1s 900us/step - los

750/750 [==============================] - 1s 883us/step - loss: 0.4310 - accuracy: 0.8203
Epoch 80/100
750/750 [==============================] - 1s 901us/step - loss: 0.4328 - accuracy: 0.8181
Epoch 81/100
750/750 [==============================] - 1s 863us/step - loss: 0.4286 - accuracy: 0.8209
Epoch 82/100
750/750 [==============================] - 1s 907us/step - loss: 0.4279 - accuracy: 0.8213
Epoch 83/100
750/750 [==============================] - 1s 893us/step - loss: 0.4257 - accuracy: 0.8219
Epoch 84/100
750/750 [==============================] - 1s 884us/step - loss: 0.4314 - accuracy: 0.8185
Epoch 85/100
750/750 [==============================] - 1s 897us/step - loss: 0.4287 - accuracy: 0.8205
Epoch 86/100
750/750 [==============================] - 1s 897us/step - loss: 0.4290 - accuracy: 0.8192
Epoch 87/100
750/750 [==============================] - 1s 927us/step - loss: 0.4256 - accuracy: 0.8228
Epoch 88/100
750/750 [==============================] - 1s 907us/step - loss:

In [17]:
pred = ann.predict(X)
print(pred)

[[1.]
 [1.]
 [1.]
 ...
 [0.]
 [1.]
 [1.]]


In [18]:
print(pred > 0.5)  

[[ True]
 [ True]
 [ True]
 ...
 [False]
 [ True]
 [ True]]


In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 0]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4657   46]
 [1153  144]]


0.8001666666666667